name: Build with PyInstaller

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout

      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Build with PyInstaller
        run: pyinstaller main.spec

      - name: Upload build artifacts
        uses: actions/upload-artifact
        with:
          name: built-executable
          path: dist/

      - name: Clean up build files
        run: |
          rmdir /S /Q build
          rmdir /S /Q __pycache__
